import type {
  SelectControlMapping,
  SensorMapping,
  TemperatureControlMapping,
} from "../types";

export const sensorMappings: SensorMapping[] = [
  {
    name: "external_temp",
    mqttUniqueId: "sensor_external_temp",
    tid: "tzew_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "fuel_level",
    mqttUniqueId: "sensor_fuel_level",
    tid: "fuel_level",
    unit: "%",
    type: "percentage",
  },
  {
    name: "boiler_temp",
    mqttUniqueId: "sensor_boiler_temp",
    tid: "tkot_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "return_temp",
    mqttUniqueId: "sensor_return_temp",
    tid: "tpow_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "dhw_temp",
    mqttUniqueId: "sensor_dhw_temp",
    tid: "tcwu_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "flue_gas_temp",
    mqttUniqueId: "sensor_flue_gas_temp",
    tid: "tsp_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "blower_speed",
    mqttUniqueId: "sensor_blower_speed",
    tid: "act_dm_speed",
    unit: "%",
    type: "percentage",
  },
  {
    name: "auto_mode",
    mqttUniqueId: "sensor_auto_mode",
    tid: "tryb_auto_state",
    type: "state",
  },
  {
    name: "pump_1",
    mqttUniqueId: "sensor_pump_1",
    tid: "out_pomp1",
    type: "state",
  },
  {
    name: "pump_2",
    mqttUniqueId: "sensor_pump_2",
    tid: "out_pomp2",
    type: "state",
  },
  {
    name: "out_cwu",
    mqttUniqueId: "sensor_out_cwu",
    tid: "out_cwu",
    type: "state",
  },
  {
    name: "boiler_setpoint",
    mqttUniqueId: "sensor_boiler_setpoint",
    tid: "kot_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "dhw_setpoint",
    mqttUniqueId: "sensor_dhw_setpoint",
    tid: "out_cwutzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "feeder_temp",
    mqttUniqueId: "sensor_feeder_temp",
    tid: "tpod_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "internal_temp",
    mqttUniqueId: "sensor_internal_temp",
    tid: "twew_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "t1_temp",
    mqttUniqueId: "sensor_t1_temp",
    tid: "t1_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "t2_temp",
    mqttUniqueId: "sensor_t2_temp",
    tid: "t2_value",
    unit: "°C",
    type: "temp",
  },
  {
    name: "external_actual",
    mqttUniqueId: "sensor_external_actual",
    tid: "tzew_act",
    unit: "°C",
    type: "temp",
  },
  {
    name: "boiler_actual",
    mqttUniqueId: "sensor_boiler_actual",
    tid: "kot_tact",
    unit: "°C",
    type: "temp",
  },
  {
    name: "dhw_actual",
    mqttUniqueId: "sensor_dhw_actual",
    tid: "cwu_tact",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_1_room_temp",
    mqttUniqueId: "sensor_circuit1_room_temp",
    tid: "ob1_pok_tact",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_1_room_setpoint",
    mqttUniqueId: "sensor_circuit1_room_setpoint",
    tid: "ob1_pok_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_1_valve_setpoint",
    mqttUniqueId: "sensor_circuit1_valve_setpoint",
    tid: "ob1_zaw4d_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_1_valve_position",
    mqttUniqueId: "sensor_circuit1_valve_position",
    tid: "ob1_zaw4d_pos",
    unit: "%",
    type: "percentage",
  },
  {
    name: "circuit_2_room_temp",
    mqttUniqueId: "sensor_circuit2_room_temp",
    tid: "ob2_pok_tact",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_2_room_setpoint",
    mqttUniqueId: "sensor_circuit2_room_setpoint",
    tid: "ob2_pok_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_2_valve_setpoint",
    mqttUniqueId: "sensor_circuit2_valve_setpoint",
    tid: "ob2_zaw4d_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_2_valve_position",
    mqttUniqueId: "sensor_circuit2_valve_position",
    tid: "ob2_zaw4d_pos",
    unit: "%",
    type: "percentage",
  },
  {
    name: "circuit_3_room_temp",
    mqttUniqueId: "sensor_circuit3_room_temp",
    tid: "ob3_pok_tact",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_3_room_setpoint",
    mqttUniqueId: "sensor_circuit3_room_setpoint",
    tid: "ob3_pok_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_3_valve_setpoint",
    mqttUniqueId: "sensor_circuit3_valve_setpoint",
    tid: "ob3_zaw4d_tzad",
    unit: "°C",
    type: "temp",
  },
  {
    name: "circuit_3_valve_position",
    mqttUniqueId: "sensor_circuit3_valve_position",
    tid: "ob3_zaw4d_pos",
    unit: "%",
    type: "percentage",
  },
  {
    name: "pod_typ",
    mqttUniqueId: "sensor_pod_typ",
    tid: "pod_typ",
    unit: "",
    type: "enum",
    values: {
      1: "retort_manual",
      2: "retort_group",
      3: "retort_ecoal",
    },
  },
  {
    name: "next_fuel_date",
    mqttUniqueId: "sensor_next_fuel_time",
    tid: "next_fuel_time",
    type: "date",
  },
  {
    name: "winter_summer_mode",
    mqttUniqueId: "sensor_winter_summer_mode",
    tid: "zima_lato_state",
    type: "state",
  },
  {
    name: "dhw_mode",
    mqttUniqueId: "sensor_dhw_mode",
    tid: "cwu_state",
    type: "enum",
    values: {
      0: "dhw_mode_off",
      1: "dhw_mode_schedule",
      2: "dhw_mode_on",
      3: "dhw_mode_boost_1h",
      4: "dhw_mode_boost_2h",
    },
  },
  {
    name: "additional_pump_function",
    mqttUniqueId: "sensor_additional_pump_function",
    tid: "pomp_ext_func",
    type: "state",
  },
  {
    name: "feeder_temp_mpl",
    mqttUniqueId: "sensor_feeder_temp_mpl",
    tid: "mpl_temp",
    unit: "°C",
    type: "temp",
  },
  {
    name: "burner_power",
    mqttUniqueId: "sensor_burner_power",
    tid: "pl_power_kw",
    unit: "kW",
  },
  {
    name: "burner_status",
    mqttUniqueId: "sensor_burner_status",
    tid: "pl_status",
    type: "enum",
    values: {
      0: "burner_status_stop",
      1: "burner_status_igniting",
      2: "burner_status_heating",
      3: "burner_status_extinguishing",
      4: "burner_status_calibration",
    },
  },
  {
    name: "pressure_difference",
    mqttUniqueId: "sensor_pressure_difference",
    tid: "dp_value",
  },
  {
    name: "ignition_count",
    mqttUniqueId: "sensor_ignition_count",
    tid: "pl_tfire",
  },
  {
    name: "feeder_runtime",
    mqttUniqueId: "sensor_feeder_runtime",
    tid: "pod_run_time_str",
    type: "state",
  },
];

export const selectControlMappings: SelectControlMapping[] = [
  {
    name: "dhw_mode",
    mqttUniqueId: "control_dhw_mode",
    setId: "cwu_state",
    currentValueId: "cwu_state",
    options: [
      { name: "dhw_mode_off", value: "0" },
      { name: "dhw_mode_schedule", value: "1" },
      { name: "dhw_mode_on", value: "2" },
      { name: "dhw_mode_boost_1h", value: "3" },
      { name: "dhw_mode_boost_2h", value: "4" },
    ],
  },
];

export const temperatureControlMappings: TemperatureControlMapping[] = [
  {
    name: "boiler_setpoint",
    mqttUniqueId: "control_boiler_setpoint",
    setId: "kot_tzad",
    readoutId: "kot_tact",
    currentSetValueId: "kot_tzad",
    unit: "°C",
    minValue: 30,
    maxValue: 90,
  },
  {
    name: "dhw_setpoint",
    mqttUniqueId: "control_dhw_setpoint",
    setId: "cwu_tzad",
    readoutId: "tcwu_value",
    currentSetValueId: "cwu_tact",
    unit: "°C",
    minValue: 30,
    maxValue: 70,
  },
  {
    name: "circuit_1_valve_setpoint",
    mqttUniqueId: "control_circuit_1_valve_setpoint",
    setId: "ob1_tzad",
    readoutId: "t1_value",
    currentSetValueId: "ob1_zaw4d_tzad",
    unit: "°C",
    minValue: 10,
    maxValue: 70,
  },
  {
    name: "circuit_1_room_setpoint",
    mqttUniqueId: "control_circuit_1_room_setpoint",
    setId: "ob1_pok_tzad",
    readoutId: "ob1_pok_tact",
    currentSetValueId: "ob1_pok_tzad",
    unit: "°C",
    minValue: 10,
    maxValue: 70,
  },
  {
    name: "circuit_2_room_setpoint",
    mqttUniqueId: "control_circuit_2_room_setpoint",
    setId: "ob2_pok_tzad",
    readoutId: "ob2_pok_tact",
    currentSetValueId: "ob2_pok_tzad",
    unit: "°C",
    minValue: 10,
    maxValue: 70,
  },
  {
    name: "circuit_3_room_setpoint",
    mqttUniqueId: "control_circuit_3_room_setpoint",
    setId: "ob3_pok_tzad",
    readoutId: "ob3_pok_tact",
    currentSetValueId: "ob3_pok_tzad",
    unit: "°C",
    minValue: 10,
    maxValue: 70,
  },
];
